version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elasticsearch
    networks:
      - elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ELASTIC_PASSWORD: aA@12345678
    volumes:
      - es_data:/usr/share/elasticsearch/data

networks:
  elastic:

volumes:
  rabbitmq_data:
    driver: local
  es_data:
    driver: local
